version: "3.7"

services:
  nginx:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /page_for_letsencrypt/www.cloudiolab.com:/usr/share/nginx/html/www.cloudiolab.com
      - /page_for_letsencrypt/me.cloudiolab.com:/usr/share/nginx/html/me.cloudiolab.com
      - /page_for_letsencrypt/docker.cloudiolab.com:/usr/share/nginx/html/docker.cloudiolab.com
      - /page_for_letsencrypt/dothings.cloudiolab.com:/usr/share/nginx/html/dothings.cloudiolab.com
      - /page_for_letsencrypt/jenkins.cloudiolab.com:/usr/share/nginx/html/jenkins.cloudiolab.com
      - registry_portus_static:/srv/Portus/public:ro
    secrets:
      - cloudiolab.com.30112019.fullchain.pem
      - cloudiolab.com.30112019.privkey.pem
      - cloudiolab.com.30112019.dhparam.pem
      - www.cloudiolab.com.30112019.fullchain.pem
      - www.cloudiolab.com.30112019.privkey.pem
      - www.cloudiolab.com.30112019.dhparam.pem
      - me.cloudiolab.com.30112019.fullchain.pem
      - me.cloudiolab.com.30112019.privkey.pem
      - me.cloudiolab.com.30112019.dhparam.pem
      - docker.cloudiolab.com.30112019.fullchain.pem
      - docker.cloudiolab.com.30112019.privkey.pem
      - docker.cloudiolab.com.30112019.dhparam.pem
      - dothings.cloudiolab.com.30112019.fullchain.pem
      - dothings.cloudiolab.com.30112019.privkey.pem
      - dothings.cloudiolab.com.30112019.dhparam.pem
      - jenkins.cloudiolab.com.30112019.fullchain.pem
      - jenkins.cloudiolab.com.30112019.privkey.pem
      - jenkins.cloudiolab.com.30112019.dhparam.pem
    configs:
      - source: nginx-30111248
        target: /etc/nginx/conf.d/default.conf
    networks:
      - cloudiolab_common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == jarvis]

networks:
  cloudiolab_common_network:
    external: true

volumes:
  registry_portus_static:
    external: true

secrets:
  cloudiolab.com.30112019.fullchain.pem:
    external: true
  cloudiolab.com.30112019.privkey.pem:
    external: true
  cloudiolab.com.30112019.dhparam.pem:
    external: true
  www.cloudiolab.com.30112019.fullchain.pem:
    external: true
  www.cloudiolab.com.30112019.privkey.pem:
    external: true
  www.cloudiolab.com.30112019.dhparam.pem:
    external: true
  me.cloudiolab.com.30112019.fullchain.pem:
    external: true
  me.cloudiolab.com.30112019.privkey.pem:
    external: true
  me.cloudiolab.com.30112019.dhparam.pem:
    external: true
  docker.cloudiolab.com.30112019.fullchain.pem:
    external: true
  docker.cloudiolab.com.30112019.privkey.pem:
    external: true
  docker.cloudiolab.com.30112019.dhparam.pem:
    external: true
  dothings.cloudiolab.com.30112019.fullchain.pem:
    external: true
  dothings.cloudiolab.com.30112019.privkey.pem:
    external: true
  dothings.cloudiolab.com.30112019.dhparam.pem:
    external: true
  jenkins.cloudiolab.com.30112019.fullchain.pem:
    external: true
  jenkins.cloudiolab.com.30112019.privkey.pem:
    external: true
  jenkins.cloudiolab.com.30112019.dhparam.pem:
    external: true

configs:
  nginx-30111248:
    file: ./nginx.conf
