version: '3.7'
services:
  portus:
    image: opensuse/portus:head
    environment:
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=/run/secrets/machine_fqdn
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=/run/secrets/database_password
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=/run/secrets/secret_key_base
      - PORTUS_KEY_PATH=/certificates/privkey.pem
      - PORTUS_PASSWORD=/run/secrets/portus_password

      # SSL
      - PORTUS_PUMA_TLS_KEY=/certificates/privkey.pem
      - PORTUS_PUMA_TLS_CERT=/certificates/fullchain.pem

      # NGinx is serving the assets instead of Puma. If you want to change this,
      # uncomment this line.
      #- RAILS_SERVE_STATIC_FILES='true'
    secrets:
      - machine_fqdn
      - database_password
      - secret_key_base
      - portus_password
    ports:
      - 3000:3000
    depends_on:
      - db
    volumes:
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/fullchain.pem:/certificates/fullchain.pem
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/privkey.pem:/certificates/privkey.pem
      - portus_static:/srv/Portus/public
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

  background:
    image: opensuse/portus:head
    depends_on:
      - portus
      - db
    environment:
      # Theoretically not needed, but cconfig's been buggy on this...
      - CCONFIG_PREFIX=PORTUS
      - PORTUS_MACHINE_FQDN_VALUE=/run/secrets/machine_fqdn
      - PORTUS_SECURITY_CLAIR_SERVER=http://clair:6060

      # DB. The password for the database should definitely not be here. You are
      # probably better off with Docker Swarm secrets.
      - PORTUS_DB_HOST=db
      - PORTUS_DB_DATABASE=portus_production
      - PORTUS_DB_PASSWORD=/run/secrets/database_password
      - PORTUS_DB_POOL=5

      # Secrets. It can possibly be handled better with Swarm's secrets.
      - PORTUS_SECRET_KEY_BASE=/run/secrets/secret_key_base
      - PORTUS_KEY_PATH=/certificates/privkey.pem
      - PORTUS_PASSWORD=/run/secrets/portus_password

      - PORTUS_BACKGROUND=true
    secrets:
      - machine_fqdn
      - database_password
      - secret_key_base
      - portus_password
    volumes:
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/privkey.pem:/certificates/privkey.pem
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]      

  db:
    image: library/mariadb:10.0.23
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    environment:
      - MYSQL_DATABASE=portus_production

      # Again, the password shouldn't be handled like this.
      - MYSQL_ROOT_PASSWORD=/run/secrets/database_password
    secrets:
      - database_password
    volumes:
      - mariadb:/var/lib/mysql
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

  registry:
    image: library/registry:2.7
    command: ["/bin/sh", "/etc/docker/registry/init"]
    environment:
      # Authentication
      REGISTRY_AUTH_TOKEN_REALM: https://docker.cloudiolab.com/v2/token
      REGISTRY_AUTH_TOKEN_SERVICE: /run/secrets/machine_fqdn
      REGISTRY_AUTH_TOKEN_ISSUER: /run/secrets/machine_fqdn
      REGISTRY_AUTH_TOKEN_ROOTCERTBUNDLE: /certificates/fullchain.pem

      # SSL
      REGISTRY_HTTP_TLS_CERTIFICATE: /certificates/fullchain.pem
      REGISTRY_HTTP_TLS_KEY: /certificates/privkey.pem

      # Portus endpoint
      REGISTRY_NOTIFICATIONS_ENDPOINTS: >
        - name: portus
          url: https://docker.cloudiolab.com/v2/webhooks/events
          timeout: 2000ms
          threshold: 5
          backoff: 1s
    secrets:
      - machine_fqdn
    volumes:
      - /docker_volumes/portus/registry:/var/lib/registry
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/fullchain.pem:/certificates/fullchain.pem
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/privkey.pem:/certificates/privkey.pem
      - ./registry/config.yml:/etc/docker/registry/config.yml:ro
      - ./registry/init:/etc/docker/registry/init:ro
    networks:
      - common_network
    ports:
      - 5000:5000
      - 5001:5001 # required to access debug service
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

  nginx:
    image: vesanthosh/reverse_proxy:latest
    volumes:
      - /root/page_for_letsencrypt:/usr/share/nginx/html
      - /docker_volumes/dhparam:/etc/ssl/certs/dhparam
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/fullchain.pem:/etc/letsencrypt/live/docker.cloudiolab.com/fullchain.pem
      - /docker_volumes/letsencrypt/etc/letsencrypt/live/docker.cloudiolab.com/privkey.pem:/etc/letsencrypt/live/docker.cloudiolab.com/privkey.pem
      - portus_static:/srv/Portus/public:ro
    ports:
      - "80:80"
      - "443:443"
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

  clair:
    image: quay.io/coreos/clair:v2.0.8
    depends_on:
      - postgres
    ports:
      - "6060-6061:6060-6061"
    volumes:
      - clair:/tmp
      - ./clair:/config
    command: [-config, /config/config.yaml]
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

  postgres:
    image: postgres:10-alpine
    environment:
      POSTGRES_PASSWORD: psqlpassword
    networks:
      - common_network
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == wNode1]

volumes:
  portus_static:
    driver: local
  mariadb:
    driver: local
  clair:
    driver: local

networks:
  common_network:

secrets:
  database_password:
    external: true
  machine_fqdn:
    external: true
  portus_password:
    external: true
  secret_key_base:
    external: true