version: '3.7'

services:
  nginx_mNode:
    image: nginx:mainline-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /page_for_letsencrypt/www.cloudiolab.com:/usr/share/nginx/html/www.cloudiolab.com
      - /page_for_letsencrypt/me.cloudiolab.com:/usr/share/nginx/html/me.cloudiolab.com
    secrets:
      - cloudiolab.com.07072019.fullchain.pem
      - cloudiolab.com.07072019.privkey.pem
      - cloudiolab.com.07072019.dhparam.pem
      - www.cloudiolab.com.07072019.fullchain.pem
      - www.cloudiolab.com.07072019.privkey.pem
      - www.cloudiolab.com.07072019.dhparam.pem
      - me.cloudiolab.com.10072019.fullchain.pem
      - me.cloudiolab.com.10072019.privkey.pem
      - me.cloudiolab.com.10072019.dhparam.pem
    configs:
      - source: nginx_mNode-11070028
        target: /etc/nginx/conf.d/default.conf
    networks:
      - cloudiolab_common_network_mNode
    deploy:
      replicas: 1
      update_config:
        failure_action: rollback
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.hostname == mNode]

networks:
  cloudiolab_common_network_mNode:
    external: true

secrets:
  cloudiolab.com.07072019.fullchain.pem:
    external: true
  cloudiolab.com.07072019.privkey.pem:
    external: true
  cloudiolab.com.07072019.dhparam.pem:
    external: true
  www.cloudiolab.com.07072019.fullchain.pem:
    external: true
  www.cloudiolab.com.07072019.privkey.pem:
    external: true
  www.cloudiolab.com.07072019.dhparam.pem:
    external: true
  me.cloudiolab.com.10072019.fullchain.pem:
    external: true
  me.cloudiolab.com.10072019.privkey.pem:
    external: true
  me.cloudiolab.com.10072019.dhparam.pem:
    external: true

configs:
  nginx_mNode-11070028:
    file: ./nginx.conf